"""
secrets_kit.exporters

Export helpers for shell runtime usage.
"""

from __future__ import annotations

import os
import shlex
import stat
from pathlib import Path
from typing import Dict


def write_protected_export(*, destination: Path, payload: bytes) -> None:
    """Atomically publish a new owner-only file, never replacing an existing path.

    The destination directory must already exist and have no symlink components.
    A pinned directory descriptor keeps publication and cleanup in that directory.
    No secret contents are included in exceptions generated by this helper.
    """
    destination = destination.expanduser().absolute()
    parent = destination.parent
    for path in (parent, *parent.parents):
        if path.is_symlink():
            raise ValueError("export_symlink_directory")
    descriptor = os.open(parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    temporary = None
    created = False
    try:
        info = os.fstat(descriptor)
        if info.st_uid != os.getuid() or stat.S_IMODE(info.st_mode) & 0o022:
            raise ValueError("export_unsafe_directory")
        # The random name is created relative to the pinned destination directory.
        temporary = ".seckit-export-" + os.urandom(16).hex()
        output = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
            0o600,
            dir_fd=descriptor,
        )
        created = True
        with os.fdopen(output, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.link(
            temporary,
            destination.name,
            src_dir_fd=descriptor,
            dst_dir_fd=descriptor,
            follow_symlinks=False,
        )
        os.fsync(descriptor)
    finally:
        if created:
            os.unlink(temporary, dir_fd=descriptor)
        os.close(descriptor)


def export_shell_lines(*, env_map: Dict[str, str]) -> str:
    """Render shell export lines with safe quoting."""
    lines = []
    for key in sorted(env_map):
        lines.append(f"export {key}={shlex.quote(env_map[key])}")
    return "\n".join(lines)


def export_dotenv_placeholders(*, keys: list[str]) -> str:
    """Render dotenv placeholders that reference the key name itself."""
    lines = []
    for key in sorted(keys):
        lines.append(f"{key}=${{{key}}}")
    return "\n".join(lines)
