"""
secrets_kit.backends.sqlite

SQLite transaction foundation exports.
"""

from __future__ import annotations

from secrets_kit.backends.sqlite.backend import (
    SQLITE_PATH_ENV,
    SqliteSecretStore,
    delete_sqlite_secret,
    get_sqlite_metadata,
    get_sqlite_secret,
    get_sqlite_secret_entry,
    is_sqlite_backend,
    list_active_sqlite_metadata,
    open_sqlite_backend,
    set_sqlite_secret,
    sqlite_path,
    sqlite_secret_exists,
)
from secrets_kit.backends.sqlite.connection import connect_sqlite, transaction
from secrets_kit.backends.sqlite.exceptions import (
    DuplicateTransactionError,
    SQLiteBackendError,
    SQLiteValidationError,
    TransactionNotFoundError,
)
from secrets_kit.backends.sqlite.hashing import (
    hash_payload,
    payload_hash_bytes_to_hex,
    payload_hash_hex_to_bytes,
    sha256_hex,
)
from secrets_kit.backends.sqlite.models import Transaction
from secrets_kit.backends.sqlite.node_identity import (
    SQLITE_NODE_IDENTITY_KEY_ENV,
    SQLiteNodeIdentitySummary,
    ensure_sqlite_node_identity,
    load_sqlite_node_identity_summary,
    sqlite_node_identity_key_path,
    validate_sqlite_node_identity,
)
from secrets_kit.backends.sqlite.peer_admission import (
    PEER_ADMISSION_ACCEPT,
    PEER_ADMISSION_REJECT,
    PEER_ADMISSION_REQUEST,
    PeerAdmissionResult,
    PeerInspection,
    PeerPublicIdentity,
    accept_peer_admission,
    create_peer_admission_transaction,
    create_signed_peer_admission_decision,
    create_signed_peer_admission_request,
    get_peer_admission,
    import_peer_admission_decision,
    list_peer_admissions,
    local_peer_public_identity,
    reject_peer_admission,
    request_peer_admission,
)
from secrets_kit.backends.sqlite.peer_endpoints import (
    PEER_ENDPOINT_EXPIRE,
    PEER_ENDPOINT_REGISTER,
    PEER_ENDPOINT_REMOVE,
    PEER_ENDPOINT_REPLACE,
    PEER_ENDPOINT_UPDATE,
    PeerEndpointRecord,
    create_peer_endpoint_transaction,
    expire_local_endpoint,
    list_active_peer_endpoints,
    list_peer_endpoint_records,
    register_local_endpoint,
    remove_local_endpoint,
    replace_local_endpoint,
    reregister_local_endpoint,
    update_local_endpoint,
)
from secrets_kit.backends.sqlite.peer_registry import (
    PeerRegistryEntry,
    get_peer_registry_entry,
    is_peer_synchronization_eligible,
    list_peer_registry_entries,
    require_peer_synchronization_eligible,
)
from secrets_kit.backends.sqlite.projections import (
    apply_secret_delete_projection,
    apply_secret_set_projection,
)
from secrets_kit.backends.sqlite.provisioning import provision_sqlite_datastore
from secrets_kit.backends.sqlite.replay import (
    SUPPORTED_REPLAY_TRANSACTION_TYPES,
    bootstrap_replay_support_rows,
    rebuild_secret_projections,
    replay_transactions,
)
from secrets_kit.backends.sqlite.schema import SCHEMA_VERSION, bootstrap_schema
from secrets_kit.backends.sqlite.serialization import canonical_json_bytes, load_canonical_json
from secrets_kit.backends.sqlite.transaction_apply import apply_transaction
from secrets_kit.backends.sqlite.transaction_engine import (
    LOCAL_TRANSACTION_POLICY,
    REMOTE_TRANSACTION_POLICY,
    REPLAY_TRANSACTION_POLICY,
    RESTORE_TRANSACTION_POLICY,
    TransactionSubmissionMode,
    TransactionSubmissionPolicy,
    TransactionSubmissionResult,
    submit_transaction,
)
from secrets_kit.backends.sqlite.transactions import (
    TransactionInspection,
    TransactionListInspection,
    create_transaction,
    get_transaction,
    insert_transaction,
    inspect_transaction,
    list_transactions_for_inspection,
    mark_transaction_applied,
    transaction_exists,
    validate_transaction,
)
from secrets_kit.backends.sqlite.validation import validate_sqlite_datastore, validate_sqlite_schema
from secrets_kit.crypto.storage.sqlite import decrypt_payload, encrypt_payload

__all__ = [
    "DuplicateTransactionError",
    "LOCAL_TRANSACTION_POLICY",
    "PEER_ADMISSION_ACCEPT",
    "PEER_ADMISSION_REJECT",
    "PEER_ADMISSION_REQUEST",
    "PEER_ENDPOINT_EXPIRE",
    "PEER_ENDPOINT_REGISTER",
    "PEER_ENDPOINT_REMOVE",
    "PEER_ENDPOINT_REPLACE",
    "PEER_ENDPOINT_UPDATE",
    "REMOTE_TRANSACTION_POLICY",
    "REPLAY_TRANSACTION_POLICY",
    "RESTORE_TRANSACTION_POLICY",
    "SCHEMA_VERSION",
    "SQLiteBackendError",
    "SQLiteValidationError",
    "SUPPORTED_REPLAY_TRANSACTION_TYPES",
    "SQLITE_NODE_IDENTITY_KEY_ENV",
    "SQLITE_PATH_ENV",
    "SqliteSecretStore",
    "SQLiteNodeIdentitySummary",
    "Transaction",
    "TransactionInspection",
    "TransactionListInspection",
    "TransactionSubmissionMode",
    "TransactionSubmissionPolicy",
    "TransactionSubmissionResult",
    "TransactionNotFoundError",
    "PeerAdmissionResult",
    "PeerInspection",
    "PeerPublicIdentity",
    "PeerRegistryEntry",
    "PeerEndpointRecord",
    "accept_peer_admission",
    "create_signed_peer_admission_decision",
    "create_signed_peer_admission_request",
    "create_peer_admission_transaction",
    "create_peer_endpoint_transaction",
    "apply_secret_delete_projection",
    "apply_secret_set_projection",
    "apply_transaction",
    "bootstrap_schema",
    "bootstrap_replay_support_rows",
    "canonical_json_bytes",
    "connect_sqlite",
    "create_transaction",
    "delete_sqlite_secret",
    "decrypt_payload",
    "encrypt_payload",
    "ensure_sqlite_node_identity",
    "get_sqlite_metadata",
    "get_sqlite_secret",
    "get_sqlite_secret_entry",
    "get_transaction",
    "get_peer_admission",
    "get_peer_registry_entry",
    "list_active_peer_endpoints",
    "list_peer_endpoint_records",
    "import_peer_admission_decision",
    "inspect_transaction",
    "hash_payload",
    "insert_transaction",
    "is_peer_synchronization_eligible",
    "list_transactions_for_inspection",
    "list_peer_admissions",
    "list_peer_registry_entries",
    "local_peer_public_identity",
    "load_sqlite_node_identity_summary",
    "mark_transaction_applied",
    "is_sqlite_backend",
    "list_active_sqlite_metadata",
    "load_canonical_json",
    "open_sqlite_backend",
    "payload_hash_bytes_to_hex",
    "payload_hash_hex_to_bytes",
    "provision_sqlite_datastore",
    "rebuild_secret_projections",
    "reject_peer_admission",
    "replay_transactions",
    "request_peer_admission",
    "register_local_endpoint",
    "replace_local_endpoint",
    "reregister_local_endpoint",
    "update_local_endpoint",
    "expire_local_endpoint",
    "remove_local_endpoint",
    "require_peer_synchronization_eligible",
    "set_sqlite_secret",
    "sha256_hex",
    "submit_transaction",
    "sqlite_path",
    "sqlite_node_identity_key_path",
    "sqlite_secret_exists",
    "transaction",
    "transaction_exists",
    "validate_transaction",
    "validate_sqlite_node_identity",
    "validate_sqlite_datastore",
    "validate_sqlite_schema",
]
