"""
secrets_kit.cli.constants.exit_codes

POSIX errno values and application-specific extensions for CLI exit status.

Every non-zero exit code must carry a specific, well-defined meaning so that
operators, automation, and monitoring systems can interpret failures without
parsing stderr. Use the closest semantic match; when no POSIX errno fits,
fall back to the application-specific extension range (150–199).

Reference: ``separation-governance/reference/POSIX-Return-Codes-and-Values.md``
"""

from __future__ import annotations

EXIT_CODES: dict[str, int] = {
    # --- POSIX errno values (primary) ---
    "EXIT_SUCCESS": 0,
    "EPERM": 1,
    "ENOENT": 2,
    "ESRCH": 3,
    "EIO": 5,
    "ENXIO": 6,
    "E2BIG": 7,
    "ENOEXEC": 8,
    "EBADF": 9,
    "ECHILD": 10,
    "EAGAIN": 35,
    "EACCES": 13,
    "EFAULT": 14,
    "EBUSY": 16,
    "EEXIST": 17,
    "EXDEV": 18,
    "ENODEV": 19,
    "ENOTDIR": 20,
    "EISDIR": 21,
    "EINVAL": 22,
    "ENFILE": 23,
    "EMFILE": 24,
    "ENOSPC": 28,
    "ESPIPE": 29,
    "EROFS": 30,
    "EPIPE": 32,
    "EDOM": 33,
    "ERANGE": 34,
    "EINPROGRESS": 36,
    "EALREADY": 37,
    "ENOTSOCK": 38,
    "EDESTADDRREQ": 39,
    "EMSGSIZE": 40,
    "EPROTOTYPE": 41,
    "ENOPROTOOPT": 42,
    "EPROTONOSUPPORT": 43,
    "ESOCKTNOSUPPORT": 44,
    "ENOTSUP": 45,
    "EOPNOTSUPP": 45,
    "EADDRINUSE": 48,
    "EADDRNOTAVAIL": 49,
    "ENETDOWN": 50,
    "ENETUNREACH": 51,
    "ENETRESET": 52,
    "ECONNABORTED": 53,
    "ECONNRESET": 54,
    "ENOBUFS": 55,
    "EISCONN": 56,
    "ENOTCONN": 57,
    "ESHUTDOWN": 58,
    "ETOOMANYREFS": 59,
    "ETIMEDOUT": 60,
    "ECONNREFUSED": 61,
    "ELOOP": 62,
    "ENAMETOOLONG": 63,
    "EHOSTDOWN": 64,
    "EHOSTUNREACH": 65,
    "ENOTEMPTY": 66,
    "EPROCLIM": 67,
    "EUSERS": 68,
    "EDQUOT": 69,
    "ESTALE": 70,
    "EREMOTE": 71,
    "EBADRPC": 72,
    "ERPCMISMATCH": 73,
    "EPROGUNAVAIL": 74,
    "EPROGMISMATCH": 75,
    "EPROCUNAVAIL": 76,
    "ENOLCK": 77,
    "ENOSYS": 78,
    "EFTYPE": 79,
    "EAUTH": 80,
    "ENEEDAUTH": 81,
    "EPWROFF": 82,
    "EDEVERR": 83,
    "EOVERFLOW": 84,
    "EBADEXEC": 85,
    "EBADARCH": 86,
    "ESHLIBVERS": 87,
    "EBADMACHO": 88,
    "ECANCELED": 89,
    "EIDRM": 90,
    "ENOMSG": 91,
    "EILSEQ": 92,
    "ENOATTR": 93,
    "EBADMSG": 94,
    "EMULTIHOP": 95,
    "ENODATA": 96,
    "ENOLINK": 97,
    "ENOSR": 98,
    "ENOSTR": 99,
    "EPROTO": 100,
    "ETIME": 101,
    "ENOPOLICY": 103,
    "ENOTRECOVERABLE": 104,
    "EOWNERDEAD": 105,
    "EQFULL": 106,
    # --- Application-specific extensions (150–199) ---
    "EAPP_BACKEND_NOT_FOUND": 150,
    "EAPP_REGISTRY_CORRUPT": 151,
    "EAPP_SYNC_CONFLICT": 152,
    "EAPP_KEYCHAIN_NOT_FOUND": 153,
    "EAPP_LAUNCHD_FAILED": 154,
    "EAPP_INJECTION_FAILED": 155,
    "EAPP_METADATA_DRIFT": 156,
    "EAPP_JOURNAL_INVALID": 157,
    "EAPP_SECURITY_CLI_MISSING": 158,
    "EAPP_PEER_NOT_FOUND": 159,
    "EAPP_BUNDLE_INVALID": 160,
    "EAPP_ENROLLMENT_FAILED": 161,
    "EAPP_ROTATION_OVERDUE": 162,
    "EAPP_EXPORT_FAILED": 163,
    "EAPP_IMPORT_FAILED": 164,
    "EAPP_CONFIG_INVALID": 165,
    "EAPP_DAEMON_NOT_RUNNING": 166,
    "EAPP_VERSION_MISMATCH": 167,
}
